### ISSUE TITLE
11/04

### ISSUE THREAD

**Issue by eooeo** [januarythirtyfirst/ivan21#7]
```yaml
start_date: 2021/4/6
due_date: 2021/4/6
progress: 0
parent: 0
dependon:
  - '6'
```
&nbsp; 
- [x] 08:00 test 26
- [x] 09:30 зубрить 
- [x] 10:00 курс
- [x] 11:00 static
- [x] 12:00 lunch
- [ ] 13:00 coding 1
- [ ] 14:00 notcoding
- [ ] 15:00 дз
- [ ] 16:00 #17#19
- [ ] 17:00 #14
- [x] 18:00 jogging
- [x] 19:00 
- [x] 20:00 sport
- [x] 21:00
